[build]
  command = "yarn build"
  publish = "public"

[build.environment]
  YARN_VERSION = "1.19.0"

[[redirects]]
  from = "https://centrifuge-documentation.netlify.com/*"
  to = "https://developer.centrifuge.io/:splat"
  status = 301
  force = true

[context.develop]
  [[redirects]]
    from = "http://staging-centrifuge-documentation.netlify.com/*"
    to = "http://develop.developer.centrifuge.io/:splat"
    status = 301
    force = true
